<a href="https://colab.research.google.com/github/plaban1981/Tensorflow2.0andKERAS/blob/master/Tensorflow_2_0_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'1.15.0'

In [2]:
!pip uninstall tensorflow

Uninstalling tensorflow-1.15.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/freeze_graph
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-1.15.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/*
Proceed (y/n)? y
y
y
  Successfully uninstalled tensorflow-1.15.0


In [3]:
!pip install tensorflow

     |████████████████████████████████| 421.8MB 40kB/s 
     |████████████████████████████████| 3.8MB 44.5MB/s 
     |████████████████████████████████| 450kB 52.0MB/s 
     |████████████████████████████████| 81kB 8.7MB/s 
ERROR: tensorboard 2.1.0 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1


**TensorFlow** is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices. Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.

Both Tensorflow 2.0 and Keras have been released for four years (Keras was released in March 2015, and Tensorflow was released in November of the same year). The rapid development of deep learning in the past days, we also know some problems of Tensorflow1.x and Keras:

* Using Tensorflow to  program static graphs, which is difficult and inconvenient for programs that are familiar with imperative programming

* Tensorflow api is powerful and flexible, but it is more complex, confusing and difficult to use.

* Keras api is productive and easy to use, but lacks flexibility for research

## Version Check

In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.1.0
Keras version: 2.2.4-tf


Tensorflow2.0 is a combination design of Tensorflow1.x and Keras. Considering user feedback and framework development over the past four years, it largely solves the above problems and will become the future machine learning platform.

#### Tensorflow 2.0 is built on the following core ideas:

- The coding is more pythonic, so that users can get the results immediately like they are programming in numpy
- Retaining the characteristics of static graphs (for performance, distributed, and production deployment), this makes TensorFlow fast, scalable, and ready for production.
- Using Keras as a high-level API for deep learning, making Tensorflow easy to use and efficient
- Make the entire framework both high-level features (easy to use, efficient, and not flexible) and low-level features (powerful and scalable, not easy to use, but very flexible)

####  Eager execution is by default in TensorFlow 2.0 and, it needs no special setup. 

The following below code can be used to find out whether a CPU or GPU is in use

In [3]:
variable = tf.Variable([3, 3])
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0?')
    print(variable.device.endswith('GPU'))
else:
    print('CPU')

GPU
GPU #0?
False


## Tensor Constant

In [4]:
var1 = tf.constant(42)
var1

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
var1.numpy()

42

In [6]:
var2 = tf.constant(1,dtype=tf.int64)
var2

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [7]:
var3 = tf.constant([[2,3],[4,5]])
var3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [9]:
var3.numpy()

array([[2, 3],
       [4, 5]], dtype=int32)

In [10]:
print('shape:',var3.shape)
print(var3.dtype)

shape: (2, 2)
<dtype: 'int32'>


##Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [11]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
print(tf.ones(shape=(3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [14]:
const1 = tf.constant([[3,4,5],[3,4,5]])
const2 = tf.constant([[1,2,5],[3,5,7]])
result = tf.add(const1,const2)
print(result)

tf.Tensor(
[[ 4  6 10]
 [ 6  9 12]], shape=(2, 3), dtype=int32)


We have defined two constants and we add one value to the other. As a result, we got a Tensor object with the result of the adding.

##Random constant

In [15]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.051677 , 1.4868445],
       [0.4935909, 1.2425239]], dtype=float32)>

In [16]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[6, 8],
       [0, 4]], dtype=int32)>

In [0]:
tf.random.set_seed(11)
random_1 = tf.random.uniform(shape=(2,2),minval=1,maxval=10,dtype=tf.int32)
random_2 = tf.random.uniform(shape=(2,2),minval=2,maxval=10,dtype=tf.int32)

In [18]:
random_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [19]:
random_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 5],
       [9, 2]], dtype=int32)>

## Variables

A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

##Declaring variables

In [20]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

* TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

##The datatype can be explicitly specified

In [21]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

In [22]:
float_var64.numpy()

89.0

TensorFlow has a large number of built-in datatypes.

- tf.float16: 16-bit half-precision floating-point.
- tf.float32: 32-bit single-precision floating-point.
-tf.float64: 64-bit double-precision floating-point.
-tf.bfloat16: 16-bit truncated floating-point.
-tf.complex64: 64-bit single-precision complex.
-tf.complex128: 128-bit double-precision complex.
-tf.int8: 8-bit signed integer.
-tf.uint8: 8-bit unsigned integer.
-tf.uint16: 16-bit unsigned integer.
-tf.uint32: 32-bit unsigned integer.
-tf.uint64: 64-bit unsigned integer.
-tf.int16: 16-bit signed integer.
-tf.int32: 32-bit signed integer.
-tf.int64: 64-bit signed integer.
-tf.bool: Boolean.
-tf.string: String.
-tf.qint8: Quantized 8-bit signed integer.
-tf.quint8: Quantized 8-bit unsigned integer.
-tf.qint16: Quantized 16-bit signed integer.
-tf.quint16: Quantized 16-bit unsigned integer.
-tf.qint32: Quantized 32-bit signed integer.
-tf.resource: Handle to a mutable resource.
-tf.variant: Values of arbitrary types.

##To reassign a variable, use var.assign()

In [23]:
var_reassign = tf.Variable(89.0)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [24]:
var_reassign.assign(98.0)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [25]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.8089824 , 1.1437266 ],
       [0.3796853 , 0.95578766]], dtype=float32)>


We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [26]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.158006  , -0.25985676],
       [-0.59844977, -0.5830384 ]], dtype=float32)>

In [0]:
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [0]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] + added_value[i,j]

In [29]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.29949635, -0.00920376],
       [-1.4293183 , -1.1614537 ]], dtype=float32)>

##Shaping a tensor

In [31]:
tensor_var = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor_var)
print(tensor_var.shape)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>
(2, 2, 3)


## Tensors can be reshaped and retain the same values which is required for constructing Neural networks.

In [32]:
tensor1 = tf.reshape(tensor_var,[2,6]) # 2 rows 6 cols
#tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [34]:
tensor2 = tf.reshape(tensor_var,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)>

##Rank of a tensor

The rank of a tensor is defined as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor.

In [35]:
tf.rank(tensor_var)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

(the shape is () because the output here is a scalar value)

##Specifying an element of a tensor

In [36]:
tensor3 = tensor_var[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

##Casting a tensor to a NumPy variable

In [37]:
print(tensor_var.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [38]:
print(tensor_var[1, 0, 2].numpy())

18.0


## Finding the size or length of a tensor

In [39]:
tensor_size = tf.size(input=tensor_var).numpy()
tensor_size

12

## Data Type of Tensor


In [40]:
tensor3.dtype

tf.float32

##Tensorflow mathematical operations

Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.

In [41]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 1.6126053  -0.12196143]
 [ 0.9344708  -0.43732217]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.2842556  -0.4905156 ]
 [ 0.7645078   0.41764784]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.3283497  -0.612477  ]
 [ 1.6989785  -0.01967433]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.7645129e+00 3.7512809e-01]
 [2.8865280e+00 3.8707929e-04]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3.774809  0.5420067]
 [5.468359  0.9805179]], shape=(2, 2), dtype=float32)


## Performing element-wise primitive tensor operations

In [42]:
tensor_var * tensor_var

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)>

## Broadcasting in Tensorflow
Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

The simplest example is multiplication of a tensor by a scalar value.

In [44]:
tensor4 = tensor_var *4
print(tensor4)

tf.Tensor(
[[[40. 44. 48.]
  [52. 56. 60.]]

 [[64. 68. 72.]
  [76. 80. 84.]]], shape=(2, 2, 3), dtype=float32)


##Transpose Matrix multiplication

In [45]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]], dtype=int32)>

## Casting a tensor to another datatype

In [46]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]], dtype=int32)>

## Casting with truncation

In [47]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

##Ragged tensors

A ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths.There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.

In [48]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


In [49]:
ragged.shape

TensorShape([5, None])

## Squared difference of tensors

In [50]:
varx = [4,5,6,1,2]
vary = 8
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36], dtype=int32)>

##Calculate the mean

##Checkpoint

In [0]:
import os
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint1 = tf.train.Checkpoint(var=variable1)
savepath= checkpoint1.save('/tmp/chkpoiint/')
variable1.assign([[0,0,0,0],[0,0,0,0]])
print(variable1)
checkpoint1.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]], dtype=int32)>


In [0]:
print(savepath)

/tmp/chkpoiint/-1


##Gradient - differntial function

In [0]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
print(a)
print(b)

tf.Tensor(
[[0.8089824  1.1437266 ]
 [0.3796853  0.95578766]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.158006   -0.25985676]
 [-0.59844977 -0.5830384 ]], shape=(2, 2), dtype=float32)


In [0]:
with tf.GradientTape() as tape:
  tape.watch(a)
  c= tf.sqrt(tf.square(a) + tf.square(b))
  print(c)
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[1.412597   1.172875  ]
 [0.70873344 1.1195819 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.57269156 0.9751479 ]
 [0.5357237  0.8537005 ]], shape=(2, 2), dtype=float32)


## Keras - High Level API for Tensorflow 2.0