<a href="https://colab.research.google.com/github/plaban1981/Tensorflow2.0andKERAS/blob/master/Tensorflow_2_0_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'1.15.0'

In [2]:
!pip uninstall tensorflow

Uninstalling tensorflow-1.15.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/freeze_graph
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-1.15.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-1.15.0


In [3]:
!pip install tensorflow

     |████████████████████████████████| 421.8MB 41kB/s 
     |████████████████████████████████| 450kB 56.1MB/s 
     |████████████████████████████████| 3.8MB 58.6MB/s 
     |████████████████████████████████| 81kB 14.3MB/s 
ERROR: tensorboard 2.1.0 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0


**TensorFlow** is an open source software library for high performance numerical computation. Its flexible architecture allows easy deployment of computation across a variety of platforms (CPUs, GPUs, TPUs), and from desktops to clusters of servers to mobile and edge devices. Originally developed by researchers and engineers from the Google Brain team within Google’s AI organization, it comes with strong support for machine learning and deep learning and the flexible numerical computation core is used across many other scientific domains.

Both Tensorflow 2.0 and Keras have been released for four years (Keras was released in March 2015, and Tensorflow was released in November of the same year). The rapid development of deep learning in the past days, we also know some problems of Tensorflow1.x and Keras:

* Using Tensorflow to  program static graphs, which is difficult and inconvenient for programs that are familiar with imperative programming

* Tensorflow api is powerful and flexible, but it is more complex, confusing and difficult to use.

* Keras api is productive and easy to use, but lacks flexibility for research

## Version Check

In [1]:
import tensorflow as tf
print("TensorFlow version: {}".format(tf.__version__))
print("Keras version: {}".format(tf.keras.__version__))

TensorFlow version: 2.1.0
Keras version: 2.2.4-tf


Tensorflow2.0 is a combination design of Tensorflow1.x and Keras. Considering user feedback and framework development over the past four years, it largely solves the above problems and will become the future machine learning platform.

#### Tensorflow 2.0 is built on the following core ideas:

- The coding is more pythonic, so that users can get the results immediately like they are programming in numpy
- Retaining the characteristics of static graphs (for performance, distributed, and production deployment), this makes TensorFlow fast, scalable, and ready for production.
- Using Keras as a high-level API for deep learning, making Tensorflow easy to use and efficient
- Make the entire framework both high-level features (easy to use, efficient, and not flexible) and low-level features (powerful and scalable, not easy to use, but very flexible)

####  Eager execution is by default in TensorFlow 2.0 and, it needs no special setup. 

The following below code can be used to find out whether a CPU or GPU is in use

In [4]:
variable = tf.Variable([3, 3])
if tf.config.list_physical_devices('GPU'):
    print('GPU')
    print('GPU #0?')
    print(variable.device)
else:
    print('CPU')

GPU
GPU #0?
/job:localhost/replica:0/task:0/device:CPU:0


## Tensor Constant

In [5]:
var1 = tf.constant(42)
var1

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
var1.numpy()

42

In [7]:
var2 = tf.constant(1,dtype=tf.int64)
var2

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [8]:
var3 = tf.constant([[2,3],[4,5]])
var3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [9]:
var3.numpy()

array([[2, 3],
       [4, 5]], dtype=int32)

In [10]:
print('shape:',var3.shape)
print(var3.dtype)

shape: (2, 2)
<dtype: 'int32'>


##Commonly used method is to generate constant tf.ones and the tf.zeros like of numpy np.ones & np.zeros

In [11]:
print(tf.ones(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [12]:
print(tf.ones(shape=(3,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [13]:
const1 = tf.constant([[3,4,5],[3,4,5]])
const2 = tf.constant([[1,2,5],[3,5,7]])
result = tf.add(const1,const2)
print(result)

tf.Tensor(
[[ 4  6 10]
 [ 6  9 12]], shape=(2, 3), dtype=int32)


We have defined two constants and we add one value to the other. As a result, we got a Tensor object with the result of the adding.

##Random constant

In [14]:
tf.random.normal(shape=(2,2),mean=0,stddev=1.3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-1.5317391 ,  0.39344198],
       [ 1.3063855 ,  0.4878637 ]], dtype=float32)>

In [15]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [4, 5]], dtype=int32)>

In [0]:
tf.random.set_seed(11)
random_1 = tf.random.uniform(shape=(2,2),minval=1,maxval=10,dtype=tf.int32)
random_2 = tf.random.uniform(shape=(2,2),minval=2,maxval=10,dtype=tf.int32)

In [17]:
random_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [18]:
random_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 5],
       [9, 2]], dtype=int32)>

## Variables

A variable is a special tensor that is used to store variable values ​​and needs to be initialized with some values

##Declaring variables

In [19]:
var0 = 24 # python variable
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 7., 8.], [9., 10., 11.] ] ]) #rank 3 tensor
var0, var1, var2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
 array([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],
 
        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]], dtype=float32)>)

* TensorFlow will infer the datatype, defaulting to tf.float32 for floats and tf.int32 for integers

##The datatype can be explicitly specified

In [21]:
float_var64 = tf.Variable(89, dtype = tf.float64)
float_var64.dtype

tf.float64

In [22]:
float_var64.numpy()

89.0

TensorFlow has a large number of built-in datatypes.

- tf.float16: 16-bit half-precision floating-point.
- tf.float32: 32-bit single-precision floating-point.
-tf.float64: 64-bit double-precision floating-point.
-tf.bfloat16: 16-bit truncated floating-point.
-tf.complex64: 64-bit single-precision complex.
-tf.complex128: 128-bit double-precision complex.
-tf.int8: 8-bit signed integer.
-tf.uint8: 8-bit unsigned integer.
-tf.uint16: 16-bit unsigned integer.
-tf.uint32: 32-bit unsigned integer.
-tf.uint64: 64-bit unsigned integer.
-tf.int16: 16-bit signed integer.
-tf.int32: 32-bit signed integer.
-tf.int64: 64-bit signed integer.
-tf.bool: Boolean.
-tf.string: String.
-tf.qint8: Quantized 8-bit signed integer.
-tf.quint8: Quantized 8-bit unsigned integer.
-tf.qint16: Quantized 16-bit signed integer.
-tf.quint16: Quantized 16-bit unsigned integer.
-tf.qint32: Quantized 32-bit signed integer.
-tf.resource: Handle to a mutable resource.
-tf.variant: Values of arbitrary types.

##To reassign a variable, use var.assign()

In [23]:
var_reassign = tf.Variable(89.0)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=89.0>

In [24]:
var_reassign.assign(98.0)
var_reassign

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=98.0>

In [25]:
initial_value = tf.random.normal(shape=(2,2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.8089824 , 1.1437266 ],
       [0.3796853 , 0.95578766]], dtype=float32)>


We can assign "=" with assign (value), or assign_add (value) with "+ =", or assign_sub (value) with "-="

In [26]:
new_value = tf.random.normal(shape=(2,2))
a.assign(new_value)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.158006  , -0.25985676],
       [-0.59844977, -0.5830384 ]], dtype=float32)>

In [0]:
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

In [0]:
added_value = tf.random.normal(shape=(2,2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i,j] == new_value[i,j] + added_value[i,j]

In [29]:
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.29949635, -0.00920376],
       [-1.4293183 , -1.1614537 ]], dtype=float32)>

##Shaping a tensor

In [30]:
tensor_var = tf.Variable([ [ [10., 11., 12.], [13., 14., 15.] ], [ [16., 17., 18.], [19., 20., 21.] ] ]) # tensor variable
print(tensor_var)
print(tensor_var.shape)

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[10., 11., 12.],
        [13., 14., 15.]],

       [[16., 17., 18.],
        [19., 20., 21.]]], dtype=float32)>
(2, 2, 3)


## Tensors can be reshaped and retain the same values which is required for constructing Neural networks.

In [31]:
tensor1 = tf.reshape(tensor_var,[2,6]) # 2 rows 6 cols
#tensor2 = tf.reshape(tensor,[1,12]) # 1 rows 12 cols
tensor1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21.]], dtype=float32)>

In [32]:
tensor2 = tf.reshape(tensor_var,[1,12]) # 1 row 12 columns
tensor2

<tf.Tensor: shape=(1, 12), dtype=float32, numpy=
array([[10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21.]],
      dtype=float32)>

##Rank of a tensor

The rank of a tensor is defined as the number of dimensions, which is the number of indices that are required to specify any particular element of that tensor.

In [33]:
tf.rank(tensor_var)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

(the shape is () because the output here is a scalar value)

##Specifying an element of a tensor

In [34]:
tensor3 = tensor_var[1, 0, 2] # slice 1, row 0, column 2
tensor3

<tf.Tensor: shape=(), dtype=float32, numpy=18.0>

##Casting a tensor to a NumPy variable

In [35]:
print(tensor_var.numpy())

[[[10. 11. 12.]
  [13. 14. 15.]]

 [[16. 17. 18.]
  [19. 20. 21.]]]


In [36]:
print(tensor_var[1, 0, 2].numpy())

18.0


## Finding the size or length of a tensor

In [38]:
tensor_size = tf.size(input=tensor_var).numpy()
tensor_size

12

## Data Type of Tensor


In [39]:
tensor3.dtype

tf.float32

##Tensorflow mathematical operations

Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU.

In [40]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a + b
d = tf.square(c)
e = tf.exp(c)
print(a)
print(b)
print(c)
print(d)
print(e)

tf.Tensor(
[[ 1.6126053  -0.12196143]
 [ 0.9344708  -0.43732217]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.2842556  -0.4905156 ]
 [ 0.7645078   0.41764784]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.3283497  -0.612477  ]
 [ 1.6989785  -0.01967433]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.7645129e+00 3.7512809e-01]
 [2.8865280e+00 3.8707929e-04]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[3.774809  0.5420067]
 [5.468359  0.9805179]], shape=(2, 2), dtype=float32)


## Performing element-wise primitive tensor operations

In [41]:
tensor_var * tensor_var

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[100., 121., 144.],
        [169., 196., 225.]],

       [[256., 289., 324.],
        [361., 400., 441.]]], dtype=float32)>

## Broadcasting in Tensorflow
Element-wise tensor operations support broadcasting in the same way that NumPy arrays do.

The simplest example is multiplication of a tensor by a scalar value.

In [42]:
tensor4 = tensor_var *4
print(tensor4)

tf.Tensor(
[[[40. 44. 48.]
  [52. 56. 60.]]

 [[64. 68. 72.]
  [76. 80. 84.]]], shape=(2, 2, 3), dtype=float32)


##Transpose Matrix multiplication

In [43]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u, tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]], dtype=int32)>

In [44]:
matrix_u 

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[6, 7, 6]], dtype=int32)>

In [45]:
matrix_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[3, 4, 3]], dtype=int32)>

In [46]:
tf.transpose(matrix_v)

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[3],
       [4],
       [3]], dtype=int32)>

## Casting a tensor to another datatype

In [47]:
i = tf.cast(tensor1, dtype=tf.int32)
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]], dtype=int32)>

## Casting with truncation

In [48]:
j = tf.cast(tf.constant(4.9), dtype=tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

##Ragged tensors

A ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various lengths.There are a variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.

In [50]:
ragged =tf.ragged.constant([[9, 7, 4, 3], [], [11, 12, 8], [3], [7,8]])
print(ragged)
print(ragged[0,:])
print(ragged[1,:])
print(ragged[2,:])
print(ragged[3,:])
print(ragged[4,:])

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>
tf.Tensor([9 7 4 3], shape=(4,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([11 12  8], shape=(3,), dtype=int32)
tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([7 8], shape=(2,), dtype=int32)


In [51]:
ragged.shape

TensorShape([5, None])

## Squared difference of tensors

In [52]:
varx = [4,5,6,1,2]
vary = 8
varz = tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36], dtype=int32)>

##Calculate the mean

#### Function available tf.reduce_mean().

tf.reduce.mean() is similar to np.mean(), except that it infers the return datatype from the input tensor, whereas np.mean allows you to specify the output type


#### tf.reduce_mean(input_tensor, axis=None, keepdims=None, name=None)

In [53]:
# Defining a constant
numbers = tf.constant([[8., 9.], [1., 2.]])
numbers

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[8., 9.],
       [1., 2.]], dtype=float32)>

##Calculate the mean across all axes

In [54]:
tf.reduce_mean(input_tensor=numbers) #default axis = None(20 /5 = 4)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

##Calculate the mean across columns (reduce rows) with this:

In [55]:
tf.reduce_mean(input_tensor=numbers,axis=0)#column wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

## When keepdims = True

In [56]:
tf.reduce_mean(input_tensor=numbers, axis=0, keepdims=True) #the reduced axis is retained with a length of 1

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

## Calculate the mean across rows (reduce columns) with this:

In [57]:
tf.reduce_mean(input_tensor=numbers, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([8.5, 1.5], dtype=float32)>

In [58]:
tf.reduce_mean(input_tensor=numbers, axis=1,keepdims=True)#the reduced axis is retained with a length of 1

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[8.5],
       [1.5]], dtype=float32)>

##Random values generation

tf.random.normal()

tf.random.normal() outputs a tensor of the given shape filled with values of the dtype type from a normal distribution.

The function is as follows:

tf.random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)

In [60]:
random_num  = tf.random.normal(shape=(3,2), mean = 0, stddev =1, dtype=tf.float32, seed=None, name=None)
print(random_num)

tf.Tensor(
[[-0.41427493  0.27209428]
 [ 0.18780643 -1.0397136 ]
 [-0.5562317  -0.03090313]], shape=(3, 2), dtype=float32)


In [61]:
tf.random.normal(shape=(3,2), mean = 10, stddev =2, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 9.789352 , 15.112456 ],
       [ 6.917881 ,  7.0220633],
       [ 8.757543 ,  9.656188 ]], dtype=float32)>

## tf.random.uniform()

The function is this:

tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None, name=None)


This outputs a tensor of the given shape filled with values from a uniform distribution in the range minval to maxval, where the lower bound is inclusive but the upper bound isn't.

In [62]:
tf.random.uniform(shape = (2,4), minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.3663169 , 0.49927068, 0.393201  , 0.7616725 ],
       [0.81794465, 0.72981584, 0.01226366, 0.9071251 ]], dtype=float32)>

##Setting the Seed

In [65]:
tf.random.set_seed(11)
rand_num1 = tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
rand_num2 = tf.random.uniform(shape=(2,2),maxval=10,dtype=tf.int32)
#call 1
print(rand_num1) 
print(rand_num2)
#Call 2
print(rand_num1) 
print(rand_num2)

tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 6]
 [5 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[9 7]
 [9 4]], shape=(2, 2), dtype=int32)


##Practical example of Random values using Dices

In [68]:
dice11 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
dice12 = tf.Variable(tf.random.uniform([10,1],minval=1,maxval=7,dtype=tf.int32))
print(dice11)
print(dice12)
# lets ADD
dice_sum1 = dice11 + dice12
print(dice_sum1)
# We've got three separate 10x1 matrices. To produce a single 10x3 matrix, we'll concatenate them along dimension 1.column wise
finale_matrix = tf.concat(values=[dice11, dice12, dice_sum1], axis=1)
print(finale_matrix)

<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[3],
       [4],
       [1],
       [5],
       [6],
       [6],
       [6],
       [1],
       [6],
       [4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(10, 1) dtype=int32, numpy=
array([[4],
       [5],
       [1],
       [5],
       [2],
       [6],
       [5],
       [4],
       [3],
       [4]], dtype=int32)>
tf.Tensor(
[[ 7]
 [ 9]
 [ 2]
 [10]
 [ 8]
 [12]
 [11]
 [ 5]
 [ 9]
 [ 8]], shape=(10, 1), dtype=int32)
tf.Tensor(
[[ 3  4  7]
 [ 4  5  9]
 [ 1  1  2]
 [ 5  5 10]
 [ 6  2  8]
 [ 6  6 12]
 [ 6  5 11]
 [ 1  4  5]
 [ 6  3  9]
 [ 4  4  8]], shape=(10, 3), dtype=int32)


## Finding the indices of the largest and smallest element

The following functions are available:

tf.argmax(input, axis=None, name=None, output_type=tf.int64 )

tf.argmin(input, axis=None, name=None, output_type=tf.int64 )

In [69]:
# 1-D tensor
tensor_1d = tf.constant([12, 11, 51, 42, 6, 16, -8, -19, 31])
print(tensor_1d)

tf.Tensor([ 12  11  51  42   6  16  -8 -19  31], shape=(9,), dtype=int32)


In [73]:
i = tf.argmax(input=tensor_1d).numpy()
print('index of max; ', i)
print('Max element: ',tensor_1d[i].numpy())

index of max;  2
Max element:  51


In [74]:
i = tf.argmin(input=tensor_1d,axis=0).numpy()
print('index of max; ', i)
print('Max element: ',tensor_1d[i].numpy())

index of max;  7
Max element:  -19


## Saving and Restoring tensor using Checkpoint

In [75]:
import os
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint1 = tf.train.Checkpoint(var=variable1)
savepath= checkpoint1.save('/tmp/chkpoiint/')
variable1.assign([[0,0,0,0],[0,0,0,0]])
print(variable1)
checkpoint1.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]], dtype=int32)>


In [76]:
print(savepath)

/tmp/chkpoiint/-1


## Using tf.function
tf.function is a function that will take a Python function and return a TensorFlow graph. 

The advantage of this is that graphs can apply optimizations and exploit parallelism in the Python function (func). tf.function is new to TensorFlow 2.

Its function is as follows:

tf.function( func=None,input_signature=None,autograph=True,experimental_autograph_options=None )

In [0]:
def f1(x,y):
  return tf.reduce_mean(input_tensor=tf.multiply(x ** 3, 6) + y**3)

func = tf.function(f1)
x = tf.constant([3.,4.])
y = tf.constant([7.,6.])

In [78]:
func(x,y).numpy()

552.5

In [79]:
f1(x,y).numpy()

552.5

In [0]:
# f1 and f2 return the same value, but f2 executes as a TensorFlow graph
assert f1(x,y).numpy() == func(x,y).numpy()
#The assert passes, so there is no output

##Calculate the gradient- differential function

Another difference from numpy is that it can automatically track the gradient of any variable.

Open one GradientTape and tape.watch() track variables through

In [81]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
print(a)
print(b)

tf.Tensor(
[[-0.41427493  0.27209428]
 [ 0.18780643 -1.0397136 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.10532369  2.5562282 ]
 [-1.5410595  -1.4889685 ]], shape=(2, 2), dtype=float32)


In [83]:
with tf.GradientTape() as tape:
  tape.watch(a)
  c= tf.sqrt(tf.square(a) + tf.square(b))
  #print(c)
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


For all variables, the calculation is tracked by default and used to find the gradient, so do not use tape.watch()

In [84]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
  c = tf.sqrt(tf.square(a) + tf.square(b))
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


You can GradientTapefind higher-order derivatives by opening a few more:

In [85]:
with tf.GradientTape() as outer_tape:
    with tf.GradientTape() as tape:
        c = tf.sqrt(tf.square(a)+tf.square(b))
        dc_da = tape.gradient(c,a)
    d2c_d2a = outer_tape.gradient(dc_da,a)
    print(d2c_d2a)

tf.Tensor(
[[0.1420312  0.3846457 ]
 [0.63471186 0.37015942]], shape=(2, 2), dtype=float32)


## Keras - High Level API for Tensorflow 2.0

## The Keras Sequential model

To build a Keras Sequential model, you add layers to it in the same order that you want the computations to be undertaken by the network.

After you have built your model, you compile it; this optimizes the computations that are to be undertaken, and is where you allocate the optimizer and the loss function you want your model to use.

The next stage is to fit the model to the data. This is commonly known as training the model, and is where all the computations take place. It is possible to present the data to the model either in batches, or all at once.

Next, you evaluate your model to establish its accuracy, loss, and other metrics. Finally, having trained your model, you can use it to make predictions on new data. So, the workflow is: build, compile, fit, evaluate, make predictions.



#### There are two ways to create a Sequential model. Let's take a look at each of them.

## Using Sequential model

* Firstly, you can pass a list of layer instances to the constructor, as in the following example.For now, we will just explain enough to allow you to understand what Using Sequential model

* Pass a list of layer instances to the constructor, as in the following example.For now, we will just explain enough to allow you to understand what is happening here.

* Acquire the data. MNIST is a dataset of hand-drawn numerals, each on a 28 x 28 pixel grid. Every individual data point is an unsigned 8-bit integer (uint8), as are the labels:is happening here.


## Loading the Dataset 

In [0]:
mnist_data = tf.keras.datasets.mnist

In [87]:
(X_train,y_train),(X_test,y_test) = mnist_data.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [88]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


##Defining Variable

In [0]:
epochs=10
batch_size = 32

## Normalize Sample data

In [0]:
# normalize all the data points and cast the labels to int64
X_train, X_test = tf.cast(X_train/255.0, tf.float32), tf.cast(X_test/255.0, tf.float32)
y_train, y_test = tf.cast(y_train,tf.int64),tf.cast(y_test,tf.int64)

##Building the Architecture

In [0]:
mnistmodel = tf.keras.models.Sequential([
                                         tf.keras.layers.Flatten(),
                                         tf.keras.layers.Dense(512,activation=tf.nn.relu),
                                         tf.keras.layers.Dropout(0.2),
                                         tf.keras.layers.Dense(10,activation=tf.nn.softmax)
                                         ])

## Compiling the model

In [0]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])

##Fitting the model

In [94]:
mnistmodel.fit(X_train,y_train, batch_size=32, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 93us/sample - loss: 0.2191 - accuracy: 0.9351
Epoch 2/5
60000/60000 [==============================] - 4s 65us/sample - loss: 0.0968 - accuracy: 0.9706
Epoch 3/5
60000/60000 [==============================] - 4s 69us/sample - loss: 0.0691 - accuracy: 0.9778
Epoch 4/5
60000/60000 [==============================] - 4s 65us/sample - loss: 0.0550 - accuracy: 0.9822
Epoch 5/5
60000/60000 [==============================] - 4s 66us/sample - loss: 0.0416 - accuracy: 0.9867


##Evaluate the mnist model

In [95]:
mnistmodel.evaluate(X_test,y_test)

10000/10000 [==============================] - 1s 59us/sample - loss: 0.0660 - accuracy: 0.9805


[0.06600366251290543, 0.9805]

##The second way to create a Sequential model

The alternative to passing a list of layers to the Sequential model's constructor is to use the add method, as follows, for the same architecture:

## Building the Architecture & Compiling

In [0]:
mnistmodel1 = tf.keras.Sequential()
mnistmodel1.add(tf.keras.layers.Flatten())
mnistmodel1.add(tf.keras.layers.Dense(512,activation=('relu')))
mnistmodel1.add(tf.keras.layers.Dropout(0.2))
mnistmodel1.add(tf.keras.layers.Dense(10,activation=tf.nn.softmax)) # Output Layer
mnistmodel1.compile(optimizer=tf.keras.optimizers.Adam(),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

## Fitting The Model

In [100]:
mnistmodel1.fit(X_train,y_train,batch_size=32,epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 4s 67us/sample - loss: 0.2176 - accuracy: 0.9361
Epoch 2/5
60000/60000 [==============================] - 4s 62us/sample - loss: 0.0970 - accuracy: 0.9706
Epoch 3/5
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0694 - accuracy: 0.9779
Epoch 4/5
60000/60000 [==============================] - 4s 61us/sample - loss: 0.0530 - accuracy: 0.9825
Epoch 5/5
60000/60000 [==============================] - 4s 62us/sample - loss: 0.0416 - accuracy: 0.9866


##Evaluate mnistmodel1

In [101]:
mnistmodel1.evaluate(X_test, y_test)

10000/10000 [==============================] - 1s 58us/sample - loss: 0.0610 - accuracy: 0.9826


[0.06102552511789254, 0.9826]

## Keras functional API

In [0]:
The functional API lets you build much more complex architectures than the simple linear stack of Sequential models we have seen previously. 

It also supports more advanced models. 

These models include multi-input and multi-output models, models with shared layers, and models with residual connections.

In [7]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_x,train_y), (test_x, test_y) = mnist.load_data()
train_x, test_x = train_x/255.0, test_x/255.0
epochs=10

11493376/11490434 [==============================] - 0s 0us/step


## Building the Architecture

In [0]:
inputs = tf.keras.Input(shape=(28,28)) # Returns a 'placeholder' tensor
x = tf.keras.layers.Flatten()(inputs)
x = tf.keras.layers.Dense(512, activation='relu',name='d1')(x)
x = tf.keras.layers.Dropout(0.2)(x)
predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')(x)
mnistmodel2 = tf.keras.Model(inputs=inputs, outputs=predictions)

##Compile and Fit

In [107]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel2.compile (optimizer= optimiser, loss='sparse_categorical_crossentropy', metrics = ['accuracy'])
mnistmodel2.fit(train_x, train_y, batch_size=32, epochs=epochs)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 4s 73us/sample - loss: 0.2184 - accuracy: 0.9358
Epoch 2/10
60000/60000 [==============================] - 4s 65us/sample - loss: 0.0978 - accuracy: 0.9706
Epoch 3/10
60000/60000 [==============================] - 4s 64us/sample - loss: 0.0697 - accuracy: 0.9779
Epoch 4/10
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0550 - accuracy: 0.9824
Epoch 5/10
60000/60000 [==============================] - 4s 67us/sample - loss: 0.0420 - accuracy: 0.9867
Epoch 6/10
60000/60000 [==============================] - 4s 65us/sample - loss: 0.0352 - accuracy: 0.9879
Epoch 7/10
60000/60000 [==============================] - 4s 67us/sample - loss: 0.0319 - accuracy: 0.9892
Epoch 8/10
60000/60000 [==============================] - 4s 67us/sample - loss: 0.0267 - accuracy: 0.9910
Epoch 9/10
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0249 - accuracy: 0.9916
Epoch 10/10
60

## Evaluate the mnistmodel3

In [108]:
mnistmodel2.evaluate(test_x, test_y)

10000/10000 [==============================] - 1s 61us/sample - loss: 0.0762 - accuracy: 0.9814


[0.07621001853927555, 0.9814]

## Subclassing the Keras Model class

In [2]:
import tensorflow as tf

In [0]:
class MNISTModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MNISTModel, self).__init__()
        # Define your layers here.
        inputs = tf.keras.Input(shape=(28,28)) # Returns a placeholder tensor
        self.x0 = tf.keras.layers.Flatten()
        self.x1 = tf.keras.layers.Dense(512, activation='relu',name='d1')
        self.x2 = tf.keras.layers.Dropout(0.2)
        self.predictions = tf.keras.layers.Dense(10,activation=tf.nn.softmax, name='d2')


    def call(self, inputs):
    # This is where to define your forward pass
    # using the layers previously defined in `__init__`
        x = self.x0(inputs)
        x = self.x1(x)
        x = self.x2(x)
        return self.predictions(x)

In [0]:
mnistmodel4 = MNISTModel()

##Compile & Fit

In [13]:
import numpy as np
batch_size = 32
steps_per_epoch = len(train_x//batch_size)
print(steps_per_epoch)
mnistmodel4.compile (optimizer= tf.keras.optimizers.Adam(), loss='sparse_categorical_crossentropy',metrics = ['accuracy'])
mnistmodel4.fit(train_x, train_y, batch_size=batch_size, epochs=epochs)

60000
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 5s 87us/sample - loss: 0.2216 - acc: 0.9339
Epoch 2/10
60000/60000 [==============================] - 4s 62us/sample - loss: 0.0956 - acc: 0.9714
Epoch 3/10
60000/60000 [==============================] - 4s 64us/sample - loss: 0.0675 - acc: 0.9788
Epoch 4/10
60000/60000 [==============================] - 4s 64us/sample - loss: 0.0528 - acc: 0.9833
Epoch 5/10
60000/60000 [==============================] - 4s 63us/sample - loss: 0.0433 - acc: 0.9854
Epoch 6/10
60000/60000 [==============================] - 4s 60us/sample - loss: 0.0354 - acc: 0.9883
Epoch 7/10
60000/60000 [==============================] - 4s 61us/sample - loss: 0.0314 - acc: 0.9894
Epoch 8/10
60000/60000 [==============================] - 4s 59us/sample - loss: 0.0253 - acc: 0.9913
Epoch 9/10
60000/60000 [==============================] - 4s 60us/sample -

##Evaluate the mnistmodel4

In [14]:
mnistmodel4.evaluate(test_x, test_y)

10000/10000 [==============================] - 0s 45us/sample - loss: 0.0689 - acc: 0.9827


[0.06885584587669163, 0.9827]