<a href="https://colab.research.google.com/github/plaban1981/Tensorflow2.0andKERAS/blob/master/Tensorflow_2_0_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
tf.__version__

'1.15.0'

In [2]:
!pip uninstall tensorflow

Uninstalling tensorflow-1.15.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/freeze_graph
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.6/dist-packages/tensorflow-1.15.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/tensorflow/*
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-1.15.0


In [3]:
!pip install tensorflow

     |████████████████████████████████| 421.8MB 38kB/s 
     |████████████████████████████████| 3.8MB 42.4MB/s 
     |████████████████████████████████| 450kB 58.2MB/s 
     |████████████████████████████████| 81kB 13.2MB/s 
ERROR: tensorboard 2.1.0 has requirement grpcio>=1.24.3, but you'll have grpcio 1.15.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement google-auth~=1.4.0, but you'll have google-auth 1.11.0 which is incompatible.
  Found existing installation: google-auth 1.4.2
    Uninstalling google-auth-1.4.2:
      Successfully uninstalled google-auth-1.4.2
  Found existing installation: tensorboard 1.15.0
    Uninstalling tensorboard-1.15.0:
      Successfully uninstalled tensorboard-1.15.0
  Found existing installation: tensorflow-estimator 1.15.1
    Uninstalling tensorflow-estimator-1.15.1:
      Successfully uninstalled tensorflow-estimator-1.15.1


In [1]:
import tensorflow as tf
tf.__version__

'2.1.0'

In [0]:
tf.random.set_seed(11)
random_1 = tf.random.uniform(shape=(2,2),minval=1,maxval=10,dtype=tf.int32)
random_2 = tf.random.uniform(shape=(2,2),minval=2,maxval=10,dtype=tf.int32)

In [3]:
random_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 6]], dtype=int32)>

In [13]:
random_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 5],
       [9, 2]], dtype=int32)>

##Checkpoint

In [4]:
import os
variable1 = tf.Variable([[5,6,9,3],[14,15,16,18]])
checkpoint1 = tf.train.Checkpoint(var=variable1)
savepath= checkpoint1.save('/tmp/chkpoiint/')
variable1.assign([[0,0,0,0],[0,0,0,0]])
print(variable1)
checkpoint1.restore(savepath)
print(variable1)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 5,  6,  9,  3],
       [14, 15, 16, 18]], dtype=int32)>


In [5]:
print(savepath)

/tmp/chkpoiint/-1


##Gradient - differntial function

In [6]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
print(a)
print(b)

tf.Tensor(
[[0.8089824  1.1437266 ]
 [0.3796853  0.95578766]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.158006   -0.25985676]
 [-0.59844977 -0.5830384 ]], shape=(2, 2), dtype=float32)


In [7]:
with tf.GradientTape() as tape:
  tape.watch(a)
  c= tf.sqrt(tf.square(a) + tf.square(b))
  print(c)
  dc_da = tape.gradient(c,a)
  print(dc_da)

tf.Tensor(
[[1.412597   1.172875  ]
 [0.70873344 1.1195819 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.57269156 0.9751479 ]
 [0.5357237  0.8537005 ]], shape=(2, 2), dtype=float32)


## Keras - High Level API for Tensorflow 2.0